In [1]:
import numpy as np
import tensorflow as tf
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import pandas as pd

c:\Users\chris\miniconda3\envs\datascience\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [14]:
A = np.array(
    [[1,2],
     [3,4]]
)

B = np.array(
    [[10,11],
     [12,13]]
)

b = np.array([2,3]).reshape(2,1)
c = np.array([2,3]).reshape(1,2)

In [4]:
A

array([[1, 2],
       [3, 4]])

$+-*/$

In [5]:
A+B

array([[11, 13],
       [15, 17]])

In [6]:
B-A

array([[9, 9],
       [9, 9]])

In [11]:
np.dot(A,B)

array([[34, 37],
       [78, 85]])

In [15]:
A @ b

array([[ 8],
       [18]])

In [16]:
b@c

array([[4, 6],
       [6, 9]])

In [17]:
c@b

array([[13]])

In [18]:
A

array([[1, 2],
       [3, 4]])

In [19]:
A.T

array([[1, 3],
       [2, 4]])

In [20]:
b.T@b

array([[13]])

In [21]:
b@b.T

array([[4, 6],
       [6, 9]])

In [22]:
C = np.arange(6).reshape(2,3)

In [23]:
C

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
def loss_ridge(b, lam):
    y_pred = X@b;
    return (y - y_pred).T @ (y - y_pred) + lam * b.T @ b

In [28]:
from scipy import optimize
from tensorflow import keras

In [30]:
A = np.arange(24).reshape(2,3,4)
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [31]:
A[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
A[0,1,:]

array([4, 5, 6, 7])

In [34]:
A.shape

(2, 3, 4)

In [36]:
B = np.arange(12).reshape(3,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
A*B

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[  0,  13,  28,  45],
        [ 64,  85, 108, 133],
        [160, 189, 220, 253]]])

In [39]:
c = np.arange(6).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
d = np.arange(3).reshape(1,3)
d

array([[0, 1, 2]])

In [44]:
c*d

array([[ 0,  1,  4],
       [ 0,  4, 10]])

In [45]:
e = np.arange(3).reshape(3,1)
e

array([[0],
       [1],
       [2]])

In [46]:
c*e

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [48]:
A.shape

(2, 3, 4)

In [57]:
A*d.reshape(1,3,1)

array([[[ 0,  0,  0,  0],
        [ 4,  5,  6,  7],
        [16, 18, 20, 22]],

       [[ 0,  0,  0,  0],
        [16, 17, 18, 19],
        [40, 42, 44, 46]]])

In [58]:
A * d[:,:,np.newaxis]

array([[[ 0,  0,  0,  0],
        [ 4,  5,  6,  7],
        [16, 18, 20, 22]],

       [[ 0,  0,  0,  0],
        [16, 17, 18, 19],
        [40, 42, 44, 46]]])

In [59]:
A*d[:,:,None]

array([[[ 0,  0,  0,  0],
        [ 4,  5,  6,  7],
        [16, 18, 20, 22]],

       [[ 0,  0,  0,  0],
        [16, 17, 18, 19],
        [40, 42, 44, 46]]])

In [61]:
year_effects = np.arange(100,600,100)
month_fixed_effects = np.arange(1,13,1)


In [62]:
year_effects

array([100, 200, 300, 400, 500])

In [70]:
total_effects = year_effects[:,None] + month_fixed_effects[None,:]
total_effects

array([[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112],
       [201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212],
       [301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312],
       [401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412],
       [501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512]])

In [71]:
total_effects.mean(axis=0)

array([301., 302., 303., 304., 305., 306., 307., 308., 309., 310., 311.,
       312.])

In [72]:
total_effects.mean(axis=1)

array([106.5, 206.5, 306.5, 406.5, 506.5])

In [73]:
model = keras.Sequential(
    [
        keras.layers.Flatten(
            input_shape = (28,28)
        ),
        keras.layers.Dense(
            128,
            activation = 'relu'
        ),
        keras.layers.Dense(
            10,
            activation = 'softmax'
        )
    ]
)

In [74]:
(train_images, train_labels), (test_images, test_labels) = keras.datasets.mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [75]:
model.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 18s 9ms/step - loss: 2.5528 - accuracy: 0.8580
Epoch 2/5
1875/1875 [==============================] - 16s 8ms/step - loss: 0.3865 - accuracy: 0.9112
Epoch 3/5
1875/1875 [==============================] - 16s 9ms/step - loss: 0.2819 - accuracy: 0.9308
Epoch 4/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.2461 - accuracy: 0.9391
Epoch 5/5
1875/1875 [==============================] - 16s 9ms/step - loss: 0.2264 - accuracy: 0.9443
